services:

    trinity.notification.entity_converter:
        class: Trinity\NotificationBundle\Notification\EntityConverter
        arguments:
            - "@trinity.notification.annotations.utils"
            - "@logger"
            - "%trinity.notification.entity_id_field%"
            - "%trinity.notification.is_client%"


    trinity.notification.services.notification_parser:
        class: Trinity\NotificationBundle\Notification\NotificationParser
        arguments:
            - "@logger"
            - "@trinity.notification.entity_converter"
            - "%trinity.notification.entity_id_field%"
            - "%trinity.notification.is_client%"
        calls:
            - [ "setEntityManager", ["@doctrine.orm.entity_manager"]]


    trinity.notification.annotations.utils:
        class: Trinity\NotificationBundle\Notification\AnnotationsUtils


    trinity.notification.utils:
        arguments:
            - "@trinity.notification.annotations.utils"
        class: Trinity\NotificationBundle\Notification\NotificationUtils


    trinity.notification.manager:
        class: Trinity\NotificationBundle\Notification\NotificationManager
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.batch_manager"


    trinity.notification.entity_listener:
        class: Trinity\NotificationBundle\EventListener\EntityListener
        arguments:
            - "@trinity.notification.manager"
            - "@trinity.notification.utils"
            - "%trinity.notification.is_client%"
        tags:
            - { name: doctrine.event_listener, event: onFlush,     priority: 255 }
            - { name: doctrine.event_listener, event: postUpdate,  priority: 200 }
            - { name: doctrine.event_listener, event: postPersist, priority: 200 }
        calls:
            - [setRequestStack, ["@request_stack"]]


    trinity.notification.terminate_listener:
        class: Trinity\NotificationBundle\EventListener\KernelTerminateListener
        arguments:
            - "@trinity.notification.manager"
            - "@logger"
            - "%kernel.debug%"
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate}


    trinity.notification.batch_manager:
        class: Trinity\NotificationBundle\Notification\BatchManager


    trinity.bunny.client:
        class: Bunny\Client
        arguments:
            - host: "%rabbit_url%"
            - port: "%rabbit_port%"
            - user: "%rabbit_user%"
            - password: "%rabbit_password%"
            - persistent: 2
            - path: "/"
