services:
    trinity.notification.facade:
        class: Trinity\NotificationBundle\Facades\NotificationFacade
        arguments:
            - "@trinity.notification.synchronization_stopper"
            - "@trinity.notification.manager"
            - "@trinity.notification.entity_alias_translator"
            - "@trinity.notificaiton.event_dispatcher"

    trinity.notification.entity_converter:
        class: Trinity\NotificationBundle\Notification\EntityConverter
        arguments:
            - "@trinity.notification.annotations.utils"
            - "@logger"
            - "%trinity.notification.entity_id_field%"
            - "%trinity.notification.is_client%"


    trinity.notification.services.notification_parser:
        class: Trinity\NotificationBundle\Notification\NotificationParser
        arguments:
            - "@logger"
            - "@trinity.notification.entity_conversion_handler"
            - "@trinity.notificaiton.event_dispatcher"
            - "@doctrine.orm.entity_manager"
            - "@trinity.notification.entity_associator"
            - "@trinity.notification.entity_alias_translator"
            - "%trinity.notification.entity_id_field%"
            - "%trinity.notification.disable_time_violations%"

    trinity.notification.annotations.utils:
        class: Trinity\NotificationBundle\Notification\AnnotationsUtils


    trinity.notification.utils:
        arguments:
            - "@trinity.notification.annotations.utils"
        class: Trinity\NotificationBundle\Notification\NotificationUtils


    trinity.notification.manager:
        class: Trinity\NotificationBundle\Notification\NotificationManager
        arguments:
            - "@trinity.notificaiton.event_dispatcher"
            - "@trinity.notification.batch_manager"

    trinity.notification.constraints:
        class: Trinity\NotificationBundle\Notification\NotificationConstraints
        arguments:
            - "%trinity.notification.is_client%"
            - "%trinity.notification.disable_time_violations%"

    trinity.notificaiton.event_dispatcher:
        class: Trinity\NotificationBundle\Notification\NotificationEventDispatcher
        arguments:
            - "@event_dispatcher"

# this event listener can not be refactored to subscriber because one class can not be symfony and doctrine subscriber
    trinity.notification.entity_listener:
        class: Trinity\NotificationBundle\EventListener\EntityListener
        arguments:
            - "@trinity.notificaiton.event_dispatcher"
            - "@trinity.notification.utils"
            - "@trinity.notification.annotations.utils"
            - "@trinity.notification.entity_converter"
            - "%trinity.notification.is_client%"
        tags:
            - { name: doctrine.event_listener, event: postRemove,  priority: 255 }
            - { name: doctrine.event_listener, event: preRemove,  priority: 255 }
            - { name: doctrine.event_listener, event: postUpdate,  priority: 200 }
            - { name: doctrine.event_listener, event: postPersist, priority: 200 }
#            - { name: kernel.event_listener,   event: trinity.notifications.enableNotification, priority: 200, method: enableNotification}
#            - { name: kernel.event_listener,   event: trinity.notifications.disableNotification, priority: 200, method: disableNotification }
        calls:
            - [setRequestStack, ["@request_stack"]]


    trinity.notification.terminate_listener:
        class: Trinity\NotificationBundle\EventListener\KernelTerminateListener
        arguments:
            - "@trinity.notification.manager"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate}

    trinity.notification.notification_events_listener:
        class: Trinity\NotificationBundle\EventListener\NotificationEventsListener
        arguments:
            - "@trinity.notification.reader"
            - "@trinity.notificaiton.event_dispatcher"
            - "@trinity.notification.manager"
            - "%trinity.notification.is_client%"
        tags:
            - { name: kernel.event_subscriber}

    trinity.notification.message_status_listener:
        class: Trinity\NotificationBundle\EventListener\MessageStatusListener
        arguments:
            - "@trinity.messages.message_sender"
            - "%trinity.notification.is_client%"
        tags:
            - { name: kernel.event_subscriber}

    trinity.notification.batch_manager:
        class: Trinity\NotificationBundle\Notification\BatchManager
        parent: "trinity.messages.message_sender"

    trinity.notification.entity_conversion_handler:
        class: Trinity\NotificationBundle\Notification\EntityConversionHandler
        arguments:
            - "@form.factory"
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.entity_alias_translator"
            - "%trinity.notification.forms%"
            - "%trinity.notification.entity_id_field%"

    trinity.notification.entity_associator:
        class: Trinity\NotificationBundle\Notification\EntityAssociator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@trinity.notification.annotations.utils"
            - "@logger"
            - "@trinity.notification.entity_alias_translator"
            - "%trinity.notification.is_client%"
            - "%trinity.notification.entity_id_field%"

    trinity.notification.reader:
        class: Trinity\NotificationBundle\Notification\NotificationReader
        arguments:
            - "@trinity.notification.services.notification_parser"
            - "@trinity.notificaiton.event_dispatcher"
            - "@trinity.messages.message_sender"
            - "@trinity.notification.entity_associator"

    trinity.notification.notification_request_listener:
        class: Trinity\NotificationBundle\EventListener\NotificationRequestListener
        arguments:
            - "@trinity.notification.notification_request_handler"
        tags:
           - { name: kernel.event_subscriber}

    trinity.notification.notification_request_handler:
        class: Trinity\NotificationBundle\Notification\NotificationRequestHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@trinity.messages.message_sender'
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.utils"
            - "@trinity.notification.entity_alias_translator"
            - "%trinity.notification.is_client%"

    trinity.bunny.client:
        class: Bunny\Client
        arguments:
            - host: "%rabbit_url%"
            - port: "%rabbit_port%"
            - user: "%rabbit_user%"
            - password: "%rabbit_password%"
            - persistent: 2
            - path: "/"

    trinity.notification.entity_alias_translator:
        class: Trinity\NotificationBundle\Services\EntityAliasTranslator
        arguments:
            - "%trinity.notification.entities%"

    trinity.notification.synchronization_stopper:
        class: Trinity\NotificationBundle\Services\SynchronizationStopper
        arguments:
            - "@trinity.messages.message_sender"
            - "@trinity.notification.entity_alias_translator"

