services:
    trinity.notification.driver.rabbit.server:
        class: Trinity\NotificationBundle\Drivers\RabbitMasterDriver
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.utils"
            - "@trinity.notification.batch_manager"
            - "@trinity.notification.notification_status_manager"
        tags:
            - { name: trinity.notification.driver }