services:
    trinity.notification.driver.rabbit.server:
        class: Trinity\NotificationBundle\Drivers\RabbitMasterDriver
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.utils"
            - "@trinity.notification.server.producer"
            - "@trinity.notification.batch_manager"
        tags:
            - { name: trinity.notification.driver }

    trinity.notification.server.setup:
        class: Trinity\NotificationBundle\RabbitMQ\ServerSetup
        arguments:
            - "@trinity.bunny.client"
            - "%trinity.notification.listening.queues%"
            - "%trinity.notification.server.to.clients.dead.letter.exchange.name%"
            - "%trinity.notification.server.to.clients.dead.letter.queue.name%"
            - "%trinity.notification.server.to.clients.exchange.name%"
            - "%trinity.notification.server.to.clients.queue.name.pattern%"
            - "%trinity.notification.clients.to.server.dead.letter.exchange.name%"
            - "%trinity.notification.clients.to.server.dead.letter.queue.name%"
            - "%trinity.notification.clients.to.server.notifications.exchange.name%"
            - "%trinity.notification.clients.to.server.notifications.queue.name%"
            - "%trinity.notification.clients.to.server.messages.exchange.name%"
            - "%trinity.notification.clients.to.server.messages.queue.name%"

    trinity.notification.server.producer:
        class: Trinity\NotificationBundle\RabbitMQ\ServerProducer
        arguments:
            - "@trinity.notification.server.setup"

    trinity.notification.server.consumer:
        class: Trinity\NotificationBundle\RabbitMQ\ServerConsumer
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.server.setup"

    trinity.notification.message_manager:
        class: Trinity\NotificationBundle\Message\MessageManager
        arguments:
            - "@trinity.notification.server.producer"
            - "@event_dispatcher"