services:

    trinity.notification.processor:
        class: Trinity\NotificationBundle\Notification\Annotations\NotificationProcessor


    trinity.notification.client_sender:
            class: Trinity\NotificationBundle\Services\NotificationManager
            arguments:
                - "@event_dispatcher"
                - "@trinity.notification.processor"


    trinity.notification.entity_listener:
          class: Trinity\NotificationBundle\EventListener\EntityListener
          arguments:
              - "@trinity.notification.client_sender"
              - "@trinity.notification.processor"
          tags:
              - { name: doctrine.event_listener, event: postUpdate,  priority: 255 }
              - { name: doctrine.event_listener, event: postPersist, priority: 255 }
              - { name: doctrine.event_listener, event: preRemove,   priority: 255 }
              - { name: doctrine.event_listener, event: preFlush,    priority: 255 }
          calls:
              - [setRequest, [@request_stack]]




