services:

    trinity.notification.entity_converter:
        class: Trinity\NotificationBundle\Notification\EntityConverter
        arguments:
            - "@trinity.notification.annotations.utils"
            - @logger
            - @doctrine.orm.entity_manager


    trinity.notification.services.notification_parser:
        class: Trinity\NotificationBundle\Notification\NotificationParser
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @trinity.notification.entity_converter
            - %necktie_client_secret%


    trinity.notification.annotations.utils:
        class: Trinity\NotificationBundle\Notification\AnnotationsUtils


    trinity.notification.utils:
        arguments:
            - "@trinity.notification.annotations.utils"
        class: Trinity\NotificationBundle\Notification\Annotations\NotificationUtils


    trinity.notification.manager:
        class: Trinity\NotificationBundle\Notification\NotificationManager
        arguments:
            - "@event_dispatcher"


    trinity.notification.entity_listener:
        class: Trinity\NotificationBundle\EventListener\EntityListener
        arguments:
            - "@trinity.notification.manager"
            - "@trinity.notification.utils"
        tags:
            - { name: doctrine.event_listener, event: postUpdate,  priority: 255 }
            - { name: doctrine.event_listener, event: postPersist, priority: 255 }
            - { name: doctrine.event_listener, event: preRemove,   priority: 255 }
            - { name: doctrine.event_listener, event: preFlush,    priority: 255 }
        calls:
            - [setRequestStack, [@request_stack]]


    trinity.notification.driver.api:
        class: Trinity\NotificationBundle\Drivers\ApiDriver\ApiDriver
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.utils"
        tags:
            - { name: trinity.notification.driver }

    trinity.notification.driver.client_api:
        class: Trinity\NotificationBundle\Drivers\ClientApiDriver\ClientApiDriver
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.utils"
        tags:
            - { name: trinity.notification.driver }
