services:

    trinity.notification.entityConverter:
        arguments:
            - "@trinity.notification.annotations.utils"
        class: Trinity\NotificationBundle\Notification\EntityConverter

    trinity.notification.annotations.utils:
        class: Trinity\NotificationBundle\Notification\AnnotationsUtils


    trinity.notification.utils:
        arguments:
            - "@trinity.notification.annotations.utils"
        class: Trinity\NotificationBundle\Notification\Annotations\NotificationUtils


    trinity.notification.manager:
        class: Trinity\NotificationBundle\Notification\NotificationManager
        arguments:
            - "%trinity.notification.driver_name%"


    trinity.notification.entity_listener:
        class: Trinity\NotificationBundle\EventListener\EntityListener
        arguments:
            - "@trinity.notification.manager"
            - "@trinity.notification.utils"
        tags:
            - { name: doctrine.event_listener, event: postUpdate,  priority: 255 }
            - { name: doctrine.event_listener, event: postPersist, priority: 255 }
            - { name: doctrine.event_listener, event: preRemove,   priority: 255 }
            - { name: doctrine.event_listener, event: preFlush,    priority: 255 }
        calls:
            - [setRequestStack, [@request_stack]]



    trinity.notification.driver.api:
        class: Trinity\NotificationBundle\Driver\ApiDriver
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.entityConverter"
            - "@trinity.notification.utils"
        tags:
            - { name: trinity.notification.driver }
