services:
    trinity.notification.driver.rabbit.client:
        class: Trinity\NotificationBundle\Drivers\RabbitClientDriver
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.utils"
            - "@trinity.notification.client.producer"
            - "@trinity.notification.batch_manager"
            - "%trinity.notification.client.id%"
        tags:
            - { name: trinity.notification.driver }

    trinity.notification.client.setup:
        class: Trinity\NotificationBundle\RabbitMQ\ClientSetup
        arguments:
            - "@trinity.bunny.client"
            - "%trinity.notification.listening.queues%"
            - "%trinity.notification.output.messages.exchange.name%"
            - "%trinity.notification.output.notifications.exchange.name%"


    trinity.notification.client.producer:
        class: Trinity\NotificationBundle\RabbitMQ\ClientProducer
        arguments:
            - "@trinity.notification.client.setup"

    trinity.notification.client.consumer:
        class: Trinity\NotificationBundle\RabbitMQ\ClientConsumer
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.client.setup"

    trinity.notification.message_manager:
        class: Trinity\NotificationBundle\Message\MessageManager
        arguments:
            - "@trinity.notification.client.producer"
            - "@event_dispatcher"