services:
    trinity.notification.driver.rabbit.client:
        class: Trinity\NotificationBundle\Drivers\RabbitClientDriver
        arguments:
            - "@event_dispatcher"
            - "@trinity.notification.entity_converter"
            - "@trinity.notification.utils"
            - "@trinity.notification.client.producer"
            - "@trinity.notification.batch_manager"
            - "%trinity.notification.client.id%"
        tags:
            - { name: trinity.notification.driver }